// Generated by Wrangler on Sun Apr 07 2024 11:35:23 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  SESSION_KV: KVNamespace
  DEV: string
  CLIENT_URL: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  SESSION_SECRET: string
  DB: D1Database
}
