// Generated by Wrangler by running `wrangler types`
interface Env {
  VALUE_FROM_CLOUDFLARE: 'Hello from Cloudflare'
  DB: D1Database
  DEV: boolean
  SESSION_SECRET: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  CLIENT_URL: string
}
